import withReact from '../../../utils/with-react';
import AXADatepicker from './index';

export default createElement => ({
  'data-test-id': dataTestId,
  inputfield,
  open,
  value,
  onChange = () => {},
  locale,
  day,
  month,
  year,
  allowedyears = [year],
  labelbuttonok = 'OK',
  labelbuttoncancel = 'Cancel',
  placeholder = 'Please select a date',
  monthtitle = 'Choose Month',
  yeartitle = 'Choose Year',
  invaliddatetext = 'Invalid date',
  id,
}) =>
  withReact(createElement)(AXADatepicker.tagName, {
    'data-test-id': dataTestId,
    inputfield,
    open,
    value,
    onChange,
    locale,
    day,
    month,
    year,
    allowedyears,
    labelbuttonok,
    labelbuttoncancel,
    placeholder,
    monthtitle,
    yeartitle,
    invaliddatetext,
    id,
    isReact: true,
  });
