language: node_js
node_js:
- '8.8.1'
script:
- npm run test
- npm run build
- node ./node_modules/prettier/bin-prettier.js --check "src/**/*.js"
deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
