export const nearCountries = [
  {
    countryCode: 'CH',
    dialCode: '+41',
    de: 'Schweiz',
    en: 'Switzerland',
    fr: 'Suisse',
    it: 'Svizzera',
  },
  {
    countryCode: 'DE',
    dialCode: '+49',
    de: 'Deutschland',
    en: 'Germany',
    fr: 'Allemagne',
    it: 'Germania',
  },
  {
    countryCode: 'FR',
    dialCode: '+33',
    de: 'Frankreich',
    en: 'France',
    fr: 'France',
    it: 'Francia',
  },
  {
    countryCode: 'AT',
    dialCode: '+43',
    de: 'Österreich',
    en: 'Austria',
    fr: 'Autriche',
    it: 'Austria',
  },
  {
    countryCode: 'IT',
    dialCode: '+39',
    de: 'Italien',
    en: 'Italy',
    fr: 'Italie',
    it: 'Italia',
  },
  {
    countryCode: 'LI',
    dialCode: '+417',
    de: 'Liechtenstein',
    en: 'Liechtenstein',
    fr: 'Liechtenstein',
    it: 'Liechtenstein',
  },
];

export const countries = [
  {
    countryCode: 'PR',
    dialCode: '+1787',
    de: 'Puerto Rico',
    en: 'Puerto Rico',
    fr: 'Porto Rico',
    it: 'Porto Rico',
  },
  {
    countryCode: 'PS',
    dialCode: '+970',
    de: 'Palästina',
    en: 'Palestine',
    fr: 'Palestine',
    it: 'Palestina',
  },
  {
    countryCode: 'PT',
    dialCode: '+351',
    de: 'Portugal',
    en: 'Portugal',
    fr: 'Portugal',
    it: 'Portogallo',
  },
  {
    countryCode: 'PW',
    dialCode: '+680',
    de: 'Palau',
    en: 'Palau',
    fr: 'Palau',
    it: 'Palau',
  },
  {
    countryCode: 'PY',
    dialCode: '+595',
    de: 'Paraguay',
    en: 'Paraguay',
    fr: 'Paraguay',
    it: 'Paraguay',
  },
  {
    countryCode: 'QA',
    dialCode: '+974',
    de: 'Qatar',
    en: 'Qatar',
    fr: 'Qatar',
    it: 'Qatar',
  },
  {
    countryCode: 'AD',
    dialCode: '+376',
    de: 'Andorra',
    en: 'Andorra',
    fr: 'Andorre',
    it: 'Andorra',
  },
  {
    countryCode: 'AE',
    dialCode: '+971',
    de: 'Vereinigte Arabische Emirate',
    en: 'United Arab Emirates',
    fr: 'Emirats Arabes Unis',
    it: 'Emirati Arabi Uniti',
  },
  {
    countryCode: 'AF',
    dialCode: '+93',
    de: 'Afghanistan',
    en: 'Afghanistan',
    fr: 'Afghanistan',
    it: 'Afganistan',
  },
  {
    countryCode: 'AG',
    dialCode: '+1268',
    de: 'Antigua und Barbuda',
    en: 'Antigua and Barbuda',
    fr: 'Antigua et Barbuda',
    it: 'Antigua e Barbuda',
  },
  {
    countryCode: 'AI',
    dialCode: '+1264',
    de: 'Anguilla',
    en: 'Anguilla',
    fr: 'Anguilla',
    it: 'Anguilla',
  },
  {
    countryCode: 'AL',
    dialCode: '+355',
    de: 'Albanien',
    en: 'Albania',
    fr: 'Albanie',
    it: 'Albania',
  },
  {
    countryCode: 'AM',
    dialCode: '+374',
    de: 'Armenien',
    en: 'Armenia',
    fr: 'Arménie',
    it: 'Armenia',
  },
  {
    countryCode: 'AO',
    dialCode: '+244',
    de: 'Angola',
    en: 'Angola',
    fr: 'Angola',
    it: 'Angola',
  },
  {
    countryCode: 'AR',
    dialCode: '+54',
    de: 'Argentinien',
    en: 'Argentina',
    fr: 'Argentine',
    it: 'Argentina',
  },
  {
    countryCode: 'AS',
    dialCode: '+685',
    de: 'Samoa, amerikanischer Teil',
    en: 'American Samoa',
    fr: 'Samoa, partie américaine',
    it: 'Samoa, parte statunitense',
  },
  {
    countryCode: 'RE',
    dialCode: '+262',
    de: 'Réunion',
    en: 'Réunion',
    fr: 'Réunion',
    it: 'Riunione',
  },
  {
    countryCode: 'AU',
    dialCode: '+61',
    de: 'Australien',
    en: 'Australia',
    fr: 'Australie',
    it: 'Australia',
  },
  {
    countryCode: 'AW',
    dialCode: '+297',
    de: 'Aruba',
    en: 'Aruba',
    fr: 'Aruba',
    it: 'Aruba',
  },
  {
    countryCode: 'AX',
    dialCode: '+358',
    de: 'Åland',
    en: 'Åland',
    fr: 'Åland',
    it: 'Åland',
  },
  {
    countryCode: 'AZ',
    dialCode: '+994',
    de: 'Aserbaidschan',
    en: 'Azerbaijan',
    fr: 'Azerbaïdjan',
    it: 'Azerbaigian',
  },
  {
    countryCode: 'RO',
    dialCode: '+40',
    de: 'Rumänien',
    en: 'Romania',
    fr: 'Roumanie',
    it: 'Romania',
  },
  {
    countryCode: 'BA',
    dialCode: '+387',
    de: 'Bosnien-Herzegowina',
    en: 'Bosnia-Herzegovina',
    fr: 'Bosnie-Herzégovine',
    it: 'Bosnia-Erzegovina',
  },
  {
    countryCode: 'BB',
    dialCode: '+1246',
    de: 'Barbados',
    en: 'Barbados',
    fr: 'Barbade',
    it: 'Barbados',
  },
  {
    countryCode: 'RS',
    dialCode: '+381',
    de: 'Serbien',
    en: 'Serbia',
    fr: 'Serbie',
    it: 'Serbia',
  },
  {
    countryCode: 'BD',
    dialCode: '+880',
    de: 'Bangladesh',
    en: 'Bangladesh',
    fr: 'Bangladesh',
    it: 'Bangladesh',
  },
  {
    countryCode: 'BE',
    dialCode: '+32',
    de: 'Belgien',
    en: 'Belgium',
    fr: 'Belgique',
    it: 'Belgio',
  },
  {
    countryCode: 'RU',
    dialCode: '+7',
    de: 'Russische Föderation',
    en: 'Russian Federation',
    fr: 'Russie (Fédération de)',
    it: 'Russia (Federazione di)',
  },
  {
    countryCode: 'BF',
    dialCode: '+226',
    de: 'Burkina Faso',
    en: 'Burkina Faso',
    fr: 'Burkina Faso',
    it: 'Burkina Faso',
  },
  {
    countryCode: 'BG',
    dialCode: '+359',
    de: 'Bulgarien',
    en: 'Bulgaria',
    fr: 'Bulgarie',
    it: 'Bulgaria',
  },
  {
    countryCode: 'RW',
    dialCode: '+250',
    de: 'Rwanda',
    en: 'Rwanda',
    fr: 'Rwanda',
    it: 'Rwanda',
  },
  {
    countryCode: 'BH',
    dialCode: '+973',
    de: 'Bahrain',
    en: 'Bahrain',
    fr: 'Bahrain',
    it: 'Bahrein',
  },
  {
    countryCode: 'BI',
    dialCode: '+257',
    de: 'Burundi',
    en: 'Burundi',
    fr: 'Burundi',
    it: 'Burundi',
  },
  {
    countryCode: 'BJ',
    dialCode: '+229',
    de: 'Benin',
    en: 'Benin',
    fr: 'Bénin',
    it: 'Benin',
  },
  {
    countryCode: 'BL',
    dialCode: '+590',
    de: 'Saint-Barthélemy',
    en: 'Saint-Barthélemy',
    fr: 'Saint-Barthélemy',
    it: 'Saint-Barthélemy',
  },
  {
    countryCode: 'BM',
    dialCode: '+1441',
    de: 'Bermuda',
    en: 'Bermuda',
    fr: 'Bermudes',
    it: 'Bermude',
  },
  {
    countryCode: 'BN',
    dialCode: '+673',
    de: 'Brunei',
    en: 'Brunei',
    fr: 'Brunéi',
    it: 'Brunei',
  },
  {
    countryCode: 'BO',
    dialCode: '+591',
    de: 'Bolivien',
    en: 'Bolivia',
    fr: 'Bolivie',
    it: 'Bolivia',
  },
  {
    countryCode: 'SA',
    dialCode: '+966',
    de: 'Saudi-Arabien',
    en: 'Saudi Arabia',
    fr: 'Arabie Saoudite',
    it: 'Arabia Saudita',
  },
  {
    countryCode: 'SB',
    dialCode: '+677',
    de: 'Salomon-Inseln',
    en: 'Salomon Islands',
    fr: 'Salomon, Iles',
    it: 'Salomone, Isole',
  },
  {
    countryCode: 'BQ',
    dialCode: '+599',
    de: 'Bonaire, Sint Eustatius und Saba',
    en: 'Bonaire, Sint Eustatius and Saba',
    fr: 'Bonaire, Saint-Eustache et Saba',
    it: 'Bonaire, Sint-Eustache e Saba',
  },
  {
    countryCode: 'BR',
    dialCode: '+55',
    de: 'Brasilien',
    en: 'Brazil',
    fr: 'Brésil',
    it: 'Brasile',
  },
  {
    countryCode: 'SC',
    dialCode: '+248',
    de: 'Seychellen',
    en: 'Seychelles',
    fr: 'Seychelles',
    it: 'Seicelle',
  },
  {
    countryCode: 'BS',
    dialCode: '+1242',
    de: 'Bahamas',
    en: 'Bahamas',
    fr: 'Bahamas',
    it: 'Bahama',
  },
  {
    countryCode: 'SD',
    dialCode: '+249',
    de: 'Sudan',
    en: 'Sudan',
    fr: 'Soudan',
    it: 'Sudan',
  },
  {
    countryCode: 'BT',
    dialCode: '+975',
    de: 'Bhutan',
    en: 'Bhutan',
    fr: 'Bhoutan',
    it: 'Bhutan',
  },
  {
    countryCode: 'SE',
    dialCode: '+46',
    de: 'Schweden',
    en: 'Sweden',
    fr: 'Suède',
    it: 'Svezia',
  },
  {
    countryCode: 'SG',
    dialCode: '+65',
    de: 'Singapur',
    en: 'Singapore',
    fr: 'Singapour',
    it: 'Singapore',
  },
  {
    countryCode: 'BW',
    dialCode: '+267',
    de: 'Botswana',
    en: 'Botswana',
    fr: 'Botswana',
    it: 'Botswana',
  },
  {
    countryCode: 'SH',
    dialCode: '+290',
    de: 'St. Helena, Ascension und Tristan da Cunha',
    en: 'Saint Helena, Ascension and Tristan da Cunha',
    fr: 'Sainte-Hélène, Ascension et Tristan da Cunha',
    it: "Sant'Elena, Ascensione e Tristan da Cunha",
  },
  {
    countryCode: 'SI',
    dialCode: '+386',
    de: 'Slowenien',
    en: 'Slovenia',
    fr: 'Slovénie',
    it: 'Slovenia',
  },
  {
    countryCode: 'BY',
    dialCode: '+375',
    de: 'Belarus',
    en: 'Belarus',
    fr: 'Bélarus',
    it: 'Bielorussia',
  },
  {
    countryCode: 'BZ',
    dialCode: '+501',
    de: 'Belize',
    en: 'Belize',
    fr: 'Belize',
    it: 'Belize',
  },
  {
    countryCode: 'SK',
    dialCode: '+421',
    de: 'Slowakei',
    en: 'Slovakia',
    fr: 'Slovaquie',
    it: 'Slovacchia',
  },
  {
    countryCode: 'SL',
    dialCode: '+232',
    de: 'Sierra Leone',
    en: 'Sierra Leone',
    fr: 'Sierra Leone',
    it: 'Sierra Leone',
  },
  {
    countryCode: 'SM',
    dialCode: '+378',
    de: 'San Marino',
    en: 'San Marino',
    fr: 'St-Marin',
    it: 'San Marino',
  },
  {
    countryCode: 'SN',
    dialCode: '+221',
    de: 'Senegal',
    en: 'Senegal',
    fr: 'Sénégal',
    it: 'Senegal',
  },
  {
    countryCode: 'SO',
    dialCode: '+252',
    de: 'Somalia',
    en: 'Somalia',
    fr: 'Somalie',
    it: 'Somalia',
  },
  {
    countryCode: 'CA',
    dialCode: '+1',
    de: 'Kanada',
    en: 'Canada',
    fr: 'Canada',
    it: 'Canada',
  },
  {
    countryCode: 'SR',
    dialCode: '+597',
    de: 'Suriname',
    en: 'Suriname',
    fr: 'Suriname',
    it: 'Suriname',
  },
  {
    countryCode: 'CC',
    dialCode: '+61',
    de: 'Kokos-Insel (Keeling)',
    en: 'Cocos (Keeling) Island',
    fr: 'Cocos (Keeling), Ile des',
    it: 'Cocos, Isola',
  },
  {
    countryCode: 'SS',
    dialCode: '+211',
    de: 'Südsudan',
    en: 'South Sudan',
    fr: 'Soudan du Sud',
    it: 'Sudan del Sud',
  },
  {
    countryCode: 'CD',
    dialCode: '+243',
    de: 'Kongo, Demokratische Republik',
    en: 'Congo, Democratic Republic',
    fr: 'Congo, République démocratique',
    it: 'Congo, Repubblica Democratica',
  },
  {
    countryCode: 'ST',
    dialCode: '+239',
    de: 'São Tomé und Príncipe',
    en: 'São Tomé and Príncipe',
    fr: 'Sao Tomé-et-Principe',
    it: 'São Tomé e Príncipe',
  },
  {
    countryCode: 'CF',
    dialCode: '+236',
    de: 'Zentralafrika',
    en: 'Central African Republic',
    fr: 'Centrafrique',
    it: 'Centrafrica',
  },
  {
    countryCode: 'SV',
    dialCode: '+503',
    de: 'El Salvador',
    en: 'El Salvador',
    fr: 'El Salvador',
    it: 'El Salvador',
  },
  {
    countryCode: 'CG',
    dialCode: '+242',
    de: 'Kongo (Republik)',
    en: 'Congo (Republic)',
    fr: 'Congo (République)',
    it: 'Congo (Repubblica)',
  },
  {
    countryCode: 'SX',
    dialCode: '+721',
    de: 'Sint Maarten (NL)',
    en: 'Sint Maarten (NL)',
    fr: 'Sint Maarten (NL)',
    it: 'Sint Maarten (NL)',
  },
  {
    countryCode: 'CI',
    dialCode: '+225',
    de: 'Elfenbeinküste',
    en: 'Ivory Coast',
    fr: "Côte d'Ivoire",
    it: "Costa d'Avorio",
  },
  {
    countryCode: 'SY',
    dialCode: '+963',
    de: 'Syrien',
    en: 'Syria',
    fr: 'Syrie',
    it: 'Siria',
  },
  {
    countryCode: 'SZ',
    dialCode: '+268',
    de: 'Swasiland',
    en: 'Swaziland',
    fr: 'Swaziland',
    it: 'Swaziland',
  },
  {
    countryCode: 'CK',
    dialCode: '+682',
    de: 'Cook-Inseln',
    en: 'Cook Islands',
    fr: 'Cook, Iles',
    it: 'Cook, Isole',
  },
  {
    countryCode: 'CL',
    dialCode: '+56',
    de: 'Chile',
    en: 'Chile',
    fr: 'Chili',
    it: 'Cile',
  },
  {
    countryCode: 'CM',
    dialCode: '+237',
    de: 'Kamerun',
    en: 'Cameroon',
    fr: 'Cameroun',
    it: 'Camerun',
  },
  {
    countryCode: 'CN',
    dialCode: '+86',
    de: 'China (Volksrepublik)',
    en: "China (People's Republic)",
    fr: 'Chine (République populaire)',
    it: 'Cina (Repubblica Popolare)',
  },
  {
    countryCode: 'CO',
    dialCode: '+57',
    de: 'Kolumbien',
    en: 'Colombia',
    fr: 'Colombie',
    it: 'Colombia',
  },
  {
    countryCode: 'CR',
    dialCode: '+506',
    de: 'Costa Rica',
    en: 'Costa Rica',
    fr: 'Costa Rica',
    it: 'Costa Rica',
  },
  {
    countryCode: 'TC',
    dialCode: '+1649',
    de: 'Turks und Caicos',
    en: 'Turks and Caicos',
    fr: 'Turques et Caïques',
    it: 'Turks e Caicos',
  },
  {
    countryCode: 'TD',
    dialCode: '+235',
    de: 'Tschad',
    en: 'Chad',
    fr: 'Tchad',
    it: 'Ciad',
  },
  {
    countryCode: 'CU',
    dialCode: '+53',
    de: 'Kuba',
    en: 'Cuba',
    fr: 'Cuba',
    it: 'Cuba',
  },
  {
    countryCode: 'TF',
    dialCode: '+672',
    de: 'Französische Süd- und Antarktisgebiete',
    en: 'French Southern and Antarctic Lands',
    fr: 'Terres australes et antarctiques françaises',
    it: 'Terre australi e antartiche francesi',
  },
  {
    countryCode: 'CV',
    dialCode: '+238',
    de: 'Kapverdische Inseln',
    en: 'Cape Verde',
    fr: 'Cap-Vert, Iles du',
    it: 'Capo Verde, Isole del',
  },
  {
    countryCode: 'TG',
    dialCode: '+228',
    de: 'Togo',
    en: 'Togo',
    fr: 'Togo',
    it: 'Togo',
  },
  {
    countryCode: 'TH',
    dialCode: '+66',
    de: 'Thailand',
    en: 'Thailand',
    fr: 'Thaïlande',
    it: 'Tailandia',
  },
  {
    countryCode: 'CW',
    dialCode: '+599',
    de: 'Curaçao',
    en: 'Curaçao',
    fr: 'Curaçao',
    it: 'Curaçao',
  },
  {
    countryCode: 'CX',
    dialCode: '+61',
    de: 'Weihnachtsinseln (indischer Ozean)',
    en: 'Christmas Island (Indian Ocean)',
    fr: 'Christmas, Ile (Océan indien)',
    it: 'Christmas, Isola (Oceano indiano)',
  },
  {
    countryCode: 'CY',
    dialCode: '+90392',
    de: 'Zypern',
    en: 'Cyprus',
    fr: 'Chypre',
    it: 'Cipro',
  },
  {
    countryCode: 'TJ',
    dialCode: '+7',
    de: 'Tadschikistan',
    en: 'Tajikistan',
    fr: 'Tadjikistan',
    it: 'Tagiskistan',
  },
  {
    countryCode: 'CZ',
    dialCode: '+42',
    de: 'Tschechische Republik',
    en: 'Czech Republic',
    fr: 'Tchèque (République)',
    it: 'Ceca (Repubblica)',
  },
  {
    countryCode: 'TK',
    dialCode: '+690',
    de: 'Tokelau',
    en: 'Tokelau',
    fr: 'Tokélaou',
    it: 'Tokelau',
  },
  {
    countryCode: 'TL',
    dialCode: '+670',
    de: 'Timor-Leste',
    en: 'Timor-Leste',
    fr: 'Timor-Leste',
    it: 'Timor-Leste',
  },
  {
    countryCode: 'TM',
    dialCode: '+7',
    de: 'Turkmenistan',
    en: 'Turkmenistan',
    fr: 'Turkménistan',
    it: 'Turkmenistan',
  },
  {
    countryCode: 'TN',
    dialCode: '+216',
    de: 'Tunesien',
    en: 'Tunisia',
    fr: 'Tunisie',
    it: 'Tunisia',
  },
  {
    countryCode: 'TO',
    dialCode: '+676',
    de: 'Tonga',
    en: 'Tonga',
    fr: 'Tonga',
    it: 'Tonga',
  },
  {
    countryCode: 'TR',
    dialCode: '+90',
    de: 'Türkei',
    en: 'Turkey',
    fr: 'Turquie',
    it: 'Turchia',
  },
  {
    countryCode: 'TT',
    dialCode: '+1868',
    de: 'Trinidad und Tobago',
    en: 'Trinidad and Tobago',
    fr: 'Trinité et Tobago',
    it: 'Trinidad e Tobago',
  },
  {
    countryCode: 'TV',
    dialCode: '+688',
    de: 'Tuvalu',
    en: 'Tuvalu',
    fr: 'Tuvalu',
    it: 'Tuvalu',
  },
  {
    countryCode: 'TW',
    dialCode: '+886',
    de: 'Taiwan (Chinesisches Taipeh)',
    en: 'Taiwan (Chinese Taipei)',
    fr: 'Taiwan (Taipei chinois)',
    it: 'Taiwan (Cina Taipei)',
  },
  {
    countryCode: 'DJ',
    dialCode: '+253',
    de: 'Djibouti',
    en: 'Djibouti',
    fr: 'Djibouti',
    it: 'Gibuti',
  },
  {
    countryCode: 'TZ',
    dialCode: '+255',
    de: 'Tansania',
    en: 'Tanzania',
    fr: 'Tanzanie',
    it: 'Tanzania',
  },
  {
    countryCode: 'DK',
    dialCode: '+45',
    de: 'Dänemark',
    en: 'Denmark',
    fr: 'Danemark',
    it: 'Danimarca',
  },
  {
    countryCode: 'DM',
    dialCode: '+1809',
    de: 'Dominica',
    en: 'Dominica',
    fr: 'Dominique',
    it: 'Dominica',
  },
  {
    countryCode: 'DO',
    dialCode: '+1809',
    de: 'Dominikanische Republik',
    en: 'Dominican Republic',
    fr: 'Dominicaine (République)',
    it: 'Dominicana (Repubblica)',
  },
  {
    countryCode: 'UA',
    dialCode: '+380',
    de: 'Ukraine',
    en: 'Ukraine',
    fr: 'Ukraine',
    it: 'Ucraina',
  },
  {
    countryCode: 'UG',
    dialCode: '+256',
    de: 'Uganda',
    en: 'Uganda',
    fr: 'Ouganda',
    it: 'Uganda',
  },
  {
    countryCode: 'DZ',
    dialCode: '+213',
    de: 'Algerien',
    en: 'Algeria',
    fr: 'Algérie',
    it: 'Algeria',
  },
  {
    countryCode: 'UM',
    dialCode: '+246',
    de: 'Amerikanische Überseeinseln, kleinere',
    en: 'United States Minor Outlying Islands',
    fr: 'Iles mineures éloignées des Etats-Unis',
    it: 'Isole Minori (USA)',
  },
  {
    countryCode: 'EC',
    dialCode: '+593',
    de: 'Ekuador',
    en: 'Ecuador',
    fr: 'Equateur',
    it: 'Equatore',
  },
  {
    countryCode: 'US',
    dialCode: '+1',
    de: 'Vereinigte Staaten von Amerika',
    en: 'United States of America',
    fr: "Etats-Unis d'Amérique",
    it: "Stati Uniti d'America",
  },
  {
    countryCode: 'EE',
    dialCode: '+372',
    de: 'Estland',
    en: 'Estonia',
    fr: 'Estonie',
    it: 'Estonia',
  },
  {
    countryCode: 'EG',
    dialCode: '+20',
    de: 'Ägypten',
    en: 'Egypt',
    fr: 'Egypte',
    it: 'Egitto',
  },
  {
    countryCode: 'EH',
    dialCode: '+212',
    de: 'Westsahara',
    en: 'Western Sahara',
    fr: 'Sahara occidental',
    it: 'Sahara Occidentale',
  },
  {
    countryCode: 'UY',
    dialCode: '+598',
    de: 'Uruguay',
    en: 'Uruguay',
    fr: 'Uruguay',
    it: 'Uruguay',
  },
  {
    countryCode: 'UZ',
    dialCode: '+7',
    de: 'Usbekistan',
    en: 'Uzbekistan',
    fr: 'Ouzbékistan',
    it: 'Uzbekistan',
  },
  {
    countryCode: 'VA',
    dialCode: '+379',
    de: 'Vatikanstadt',
    en: 'Vatican City',
    fr: 'Cité du Vatican',
    it: 'Città del Vaticano',
  },
  {
    countryCode: 'ER',
    dialCode: '+291',
    de: 'Eritrea',
    en: 'Eritrea',
    fr: 'Erythrée',
    it: 'Eritrea',
  },
  {
    countryCode: 'VC',
    dialCode: '+1',
    de: 'St. Vincent und die Grenadinen',
    en: 'Saint Vincent and the Grenadines',
    fr: 'Saint-Vincent-et-les-Grenadines',
    it: 'Saint Vincent e Grenadine',
  },
  {
    countryCode: 'ES',
    dialCode: '+34',
    de: 'Spanien',
    en: 'Spain',
    fr: 'Espagne',
    it: 'Spagna',
  },
  {
    countryCode: 'ET',
    dialCode: '+251',
    de: 'Äthiopien',
    en: 'Ethiopia',
    fr: 'Ethiopie',
    it: 'Etiopia',
  },
  {
    countryCode: 'VE',
    dialCode: '+58',
    de: 'Venezuela',
    en: 'Venezuela',
    fr: 'Venezuela',
    it: 'Venezuela',
  },
  {
    countryCode: 'VG',
    dialCode: '+84',
    de: 'Britische Jungferninseln',
    en: 'British Virgin Islands',
    fr: 'IIes Vierges britanniques',
    it: 'Isole Vergini britanniche',
  },
  {
    countryCode: 'VI',
    dialCode: '+84',
    de: 'Jungferninseln (USA)',
    en: 'Virgin Islands (USA)',
    fr: 'Iles Vierges (Etats-Unis)',
    it: 'Isole Vergini (USA)',
  },
  {
    countryCode: 'VN',
    dialCode: '+84',
    de: 'Vietnam',
    en: 'Vietnam',
    fr: 'Viêt-Nam',
    it: 'Vietnam',
  },
  {
    countryCode: 'VU',
    dialCode: '+678',
    de: 'Vanuatu',
    en: 'Vanuatu',
    fr: 'Vanuatu',
    it: 'Vanuatu',
  },
  {
    countryCode: 'FI',
    dialCode: '+358',
    de: 'Finnland',
    en: 'Finland',
    fr: 'Finlande',
    it: 'Finlandia',
  },
  {
    countryCode: 'FJ',
    dialCode: '+679',
    de: 'Fidschi',
    en: 'Fiji',
    fr: 'Fidji',
    it: 'Figi',
  },
  {
    countryCode: 'FK',
    dialCode: '+500',
    de: 'Falkland-Inseln',
    en: 'Falkland Islands',
    fr: 'Falkland, Iles',
    it: 'Falkland, Isole',
  },
  {
    countryCode: 'FM',
    dialCode: '+691',
    de: 'Mikronesien (Föderierte Staaten von)',
    en: 'Micronesia (Federated States OF)',
    fr: 'Micronésie (Etats fédérés)',
    it: 'Micronesia (Stati federati)',
  },
  {
    countryCode: 'FO',
    dialCode: '+298',
    de: 'Färöer-Inseln',
    en: 'Faroe Islands',
    fr: 'Féroé, Iles',
    it: 'Faeröer, Isole',
  },
  {
    countryCode: 'WF',
    dialCode: '+681',
    de: 'Wallis und Futuna',
    en: 'Wallis and Futuna Islands',
    fr: 'Wallis et Futuna',
    it: 'Wallis e Futuna',
  },
  {
    countryCode: 'GA',
    dialCode: '+241',
    de: 'Gabun',
    en: 'Gabon',
    fr: 'Gabon',
    it: 'Gabon',
  },
  {
    countryCode: 'GB',
    dialCode: '+44',
    de: 'Grossbritannien und Nordirland',
    en: 'Great Britain and Northern Ireland',
    fr: 'Grande-Bretagne et Irlande du Nord',
    it: 'Gran Bretagna e Irlanda del Nord',
  },
  {
    countryCode: 'WS',
    dialCode: '+685',
    de: 'Samoa',
    en: 'Samoa',
    fr: 'Samoa',
    it: 'Samoa',
  },
  {
    countryCode: 'GD',
    dialCode: '+1473',
    de: 'Grenada',
    en: 'Grenada',
    fr: 'Grenade',
    it: 'Grenada',
  },
  {
    countryCode: 'GE',
    dialCode: '+7880',
    de: 'Georgien',
    en: 'Georgia',
    fr: 'Géorgie',
    it: 'Georgia',
  },
  {
    countryCode: 'GF',
    dialCode: '+594',
    de: 'Französisch-Guyana',
    en: 'French Guiana',
    fr: 'Guyane française',
    it: 'Guiana Francese',
  },
  {
    countryCode: 'GG',
    dialCode: '+44',
    de: 'Guernsey',
    en: 'Guernsey',
    fr: 'Guernsey',
    it: 'Guernsey',
  },
  {
    countryCode: 'GH',
    dialCode: '+233',
    de: 'Ghana',
    en: 'Ghana',
    fr: 'Ghana',
    it: 'Ghana',
  },
  {
    countryCode: 'GI',
    dialCode: '+350',
    de: 'Gibraltar',
    en: 'Gibraltar',
    fr: 'Gibraltar',
    it: 'Gibilterra',
  },
  {
    countryCode: 'GL',
    dialCode: '+299',
    de: 'Grönland',
    en: 'Greenland',
    fr: 'Groenland',
    it: 'Groenlandia',
  },
  {
    countryCode: 'GM',
    dialCode: '+220',
    de: 'Gambia',
    en: 'Gambia',
    fr: 'Gambie',
    it: 'Gambia',
  },
  {
    countryCode: 'GN',
    dialCode: '+224',
    de: 'Guinea (Republik)',
    en: 'Guinea (Republic)',
    fr: 'Guinée (République)',
    it: 'Guinea (Repubblica)',
  },
  {
    countryCode: 'GP',
    dialCode: '+590',
    de: 'Guadeloupe',
    en: 'Guadeloupe',
    fr: 'Guadeloupe',
    it: 'Guadalupa',
  },
  {
    countryCode: 'GQ',
    dialCode: '+240',
    de: 'Äquatorial-Guinea',
    en: 'Equatorial Guinea',
    fr: 'Guinée équatoriale',
    it: 'Guinea equatoriale',
  },
  {
    countryCode: 'GR',
    dialCode: '+30',
    de: 'Griechenland',
    en: 'Greece',
    fr: 'Grèce',
    it: 'Grecia',
  },
  {
    countryCode: 'GS',
    dialCode: '+500',
    de: 'Südgeorgien und die südlichen Sandwichinseln',
    en: 'South Georgia and the south Sandwich Islands',
    fr: 'Géorgie du sud et les îles Sandwich du sud',
    it: 'Georgia australe e le isole Sandwich australe',
  },
  {
    countryCode: 'GT',
    dialCode: '+502',
    de: 'Guatemala',
    en: 'Guatemala',
    fr: 'Guatemala',
    it: 'Guatemala',
  },
  {
    countryCode: 'GU',
    dialCode: '+671',
    de: 'Guam',
    en: 'Guam',
    fr: 'Guam',
    it: 'Guam',
  },
  {
    countryCode: 'GW',
    dialCode: '+245',
    de: 'Guinea-Bissau',
    en: 'Guinea-Bissau',
    fr: 'Guinée-Bissau',
    it: 'Guinea-Bissau',
  },
  {
    countryCode: 'GY',
    dialCode: '+592',
    de: 'Guyana',
    en: 'Guyana',
    fr: 'Guyane',
    it: 'Guiana',
  },
  {
    countryCode: 'ZZ',
    dialCode: '+383',
    de: 'Kosovo',
    en: 'Kosovo',
    fr: 'Kosovo',
    it: 'Kosovo',
  },
  {
    countryCode: 'XY',
    dialCode: '',
    de: 'unbekannt',
    en: 'unknown',
    fr: 'inconnu',
    it: 'sconosciuto',
  },
  {
    countryCode: 'HK',
    dialCode: '+852',
    de: 'Hongkong',
    en: 'Hong Kong',
    fr: 'Hong-Kong',
    it: 'Hongkong',
  },
  {
    countryCode: 'HN',
    dialCode: '+504',
    de: 'Honduras',
    en: 'Honduras',
    fr: 'Honduras',
    it: 'Honduras',
  },
  {
    countryCode: 'HR',
    dialCode: '+385',
    de: 'Kroatien',
    en: 'Croatia',
    fr: 'Croatie',
    it: 'Croazia',
  },
  {
    countryCode: 'HT',
    dialCode: '+509',
    de: 'Haiti',
    en: 'Haiti',
    fr: 'Haïti',
    it: 'Haiti',
  },
  {
    countryCode: 'YE',
    dialCode: '+969',
    de: 'Jemen',
    en: 'Yemen',
    fr: 'Yémen',
    it: 'Yemen',
  },
  {
    countryCode: 'HU',
    dialCode: '+36',
    de: 'Ungarn',
    en: 'Hungary',
    fr: 'Hongrie',
    it: 'Ungheria',
  },
  {
    countryCode: 'ID',
    dialCode: '+62',
    de: 'Indonesien',
    en: 'Indonesia',
    fr: 'Indonésie',
    it: 'Indonesia',
  },
  {
    countryCode: 'YT',
    dialCode: '+269',
    de: 'Mayotte',
    en: 'Mayotte',
    fr: 'Mayotte',
    it: 'Mayotte',
  },
  {
    countryCode: 'IE',
    dialCode: '+353',
    de: 'Irland',
    en: 'Ireland',
    fr: 'Irlande',
    it: 'Irlanda',
  },
  {
    countryCode: 'IL',
    dialCode: '+972',
    de: 'Israel',
    en: 'Israel',
    fr: 'Israël',
    it: 'Israele',
  },
  {
    countryCode: 'IM',
    dialCode: '+44',
    de: 'Man, Insel',
    en: 'Isle of Man',
    fr: 'Man, Ile de',
    it: 'Man, Isola di',
  },
  {
    countryCode: 'IN',
    dialCode: '+91',
    de: 'Indien',
    en: 'India',
    fr: 'Inde',
    it: 'India',
  },
  {
    countryCode: 'IO',
    dialCode: '+246',
    de: 'Britisches Territorium im Indischen Ozean',
    en: 'British Indian Ocean Territory',
    fr: "Territoire britannique de l'océan Indien",
    it: "Territorio britannico dell'Oceano Indiano",
  },
  {
    countryCode: 'ZA',
    dialCode: '+27',
    de: 'Südafrika',
    en: 'South Africa',
    fr: 'Afrique du Sud',
    it: 'Sudafrica',
  },
  {
    countryCode: 'IQ',
    dialCode: '+964',
    de: 'Irak',
    en: 'Iraq',
    fr: 'Iraq',
    it: 'Iraq',
  },
  {
    countryCode: 'IR',
    dialCode: '+98',
    de: 'Iran',
    en: 'Iran',
    fr: 'Iran',
    it: 'Iran',
  },
  {
    countryCode: 'IS',
    dialCode: '+354',
    de: 'Island',
    en: 'Iceland',
    fr: 'Islande',
    it: 'Islanda',
  },
  {
    countryCode: 'ZM',
    dialCode: '+260',
    de: 'Sambia',
    en: 'Zambia',
    fr: 'Zambie',
    it: 'Zambia',
  },
  {
    countryCode: 'JE',
    dialCode: '+44',
    de: 'Jersey',
    en: 'Jersey',
    fr: 'Jersey',
    it: 'Jersey',
  },
  {
    countryCode: 'ZW',
    dialCode: '+263',
    de: 'Zimbabwe',
    en: 'Zimbabwe',
    fr: 'Zimbabwe',
    it: 'Zimbabwe',
  },
  {
    countryCode: 'JM',
    dialCode: '+1876',
    de: 'Jamaika',
    en: 'Jamaica',
    fr: 'Jamaïque',
    it: 'Giamaica',
  },
  {
    countryCode: 'JO',
    dialCode: '+962',
    de: 'Jordanien',
    en: 'Jordan',
    fr: 'Jordanie',
    it: 'Giordania',
  },
  {
    countryCode: 'JP',
    dialCode: '+81',
    de: 'Japan',
    en: 'Japan',
    fr: 'Japon',
    it: 'Giappone',
  },
  {
    countryCode: 'KE',
    dialCode: '+254',
    de: 'Kenia',
    en: 'Kenya',
    fr: 'Kenya',
    it: 'Kenya',
  },
  {
    countryCode: 'KG',
    dialCode: '+996',
    de: 'Kirgisistan',
    en: 'Kyrgyzstan',
    fr: 'Kirghizistan',
    it: 'Kirghizistan',
  },
  {
    countryCode: 'KH',
    dialCode: '+855',
    de: 'Kambodscha',
    en: 'Cambodia',
    fr: 'Cambodge',
    it: 'Cambogia',
  },
  {
    countryCode: 'KI',
    dialCode: '+686',
    de: 'Kiribati',
    en: 'Kiribati',
    fr: 'Kiribati',
    it: 'Kiribati',
  },
  {
    countryCode: 'KM',
    dialCode: '+269',
    de: 'Komoren',
    en: 'Comoros',
    fr: 'Comores',
    it: 'Comore',
  },
  {
    countryCode: 'KN',
    dialCode: '+1869',
    de: 'St. Christoph (St. Kitts) und Nevis',
    en: 'St. Christopher (St. Kitts) and Nevis',
    fr: 'St. Christophe (St. Kitts) et Nevis',
    it: 'San Cristoforo (St. Kitts) e Nevis',
  },
  {
    countryCode: 'KP',
    dialCode: '+850',
    de: 'Korea, demokratische Volksrepublik (Nordkorea)',
    en: "Korea, Democratic People's Republic of (North Korea)",
    fr: 'Corée, République populaire démocratique (Corée du Nord)',
    it: 'Corea, Repubblica popolare democratica (Corea del Nord)',
  },
  {
    countryCode: 'KR',
    dialCode: '+82',
    de: 'Korea, Republik (Südkorea)',
    en: 'Korea, Republic of (South Korea)',
    fr: 'Corée, République (Corée du Sud)',
    it: 'Corea, Repubblica (Corea del Sud)',
  },
  {
    countryCode: 'KW',
    dialCode: '+965',
    de: 'Kuwait',
    en: 'Kuwait',
    fr: 'Kuwait',
    it: 'Kuwait',
  },
  {
    countryCode: 'KY',
    dialCode: '+1345',
    de: 'Cayman',
    en: 'Cayman Islands',
    fr: 'Cayman',
    it: 'Cayman',
  },
  {
    countryCode: 'KZ',
    dialCode: '+7',
    de: 'Kasachstan',
    en: 'Kazakhstan',
    fr: 'Kazakhstan',
    it: 'Kazakistan',
  },
  {
    countryCode: 'LA',
    dialCode: '+856',
    de: 'Laos',
    en: 'Laos',
    fr: 'Laos',
    it: 'Laos',
  },
  {
    countryCode: 'LB',
    dialCode: '+961',
    de: 'Libanon',
    en: 'Lebanon',
    fr: 'Liban',
    it: 'Libano',
  },
  {
    countryCode: 'LC',
    dialCode: '+1',
    de: 'St. Lucia',
    en: 'St. Lucia',
    fr: 'St. Lucie',
    it: 'St. Lucia',
  },
  {
    countryCode: 'LK',
    dialCode: '+94',
    de: 'Sri Lanka',
    en: 'Sri Lanka',
    fr: 'Sri Lanka',
    it: 'Sri Lanka',
  },
  {
    countryCode: 'LR',
    dialCode: '+231',
    de: 'Liberia',
    en: 'Liberia',
    fr: 'Libéria',
    it: 'Liberia',
  },
  {
    countryCode: 'LS',
    dialCode: '+266',
    de: 'Lesotho',
    en: 'Lesotho',
    fr: 'Lesotho',
    it: 'Lesotho',
  },
  {
    countryCode: 'LT',
    dialCode: '+370',
    de: 'Litauen',
    en: 'Lithuania',
    fr: 'Lituanie',
    it: 'Lituania',
  },
  {
    countryCode: 'LU',
    dialCode: '+352',
    de: 'Luxemburg',
    en: 'Luxembourg',
    fr: 'Luxembourg',
    it: 'Lussemburgo',
  },
  {
    countryCode: 'LV',
    dialCode: '+371',
    de: 'Lettland',
    en: 'Latvia',
    fr: 'Lettonie',
    it: 'Lettonia',
  },
  {
    countryCode: 'LY',
    dialCode: '+218',
    de: 'Libyen',
    en: 'Libya',
    fr: 'Libye',
    it: 'Libia',
  },
  {
    countryCode: 'MA',
    dialCode: '+212',
    de: 'Marokko',
    en: 'Morocco',
    fr: 'Maroc',
    it: 'Marocco',
  },
  {
    countryCode: 'MC',
    dialCode: '+377',
    de: 'Monaco',
    en: 'Monaco',
    fr: 'Monaco',
    it: 'Monaco',
  },
  {
    countryCode: 'MD',
    dialCode: '+373',
    de: 'Moldova',
    en: 'Moldova',
    fr: 'Moldova',
    it: 'Moldova',
  },
  {
    countryCode: 'ME',
    dialCode: '+382',
    de: 'Montenegro',
    en: 'Montenegro',
    fr: 'Monténégro',
    it: 'Montenegro',
  },
  {
    countryCode: 'MF',
    dialCode: '+590',
    de: 'Saint-Martin (FR)',
    en: 'Saint-Martin (FR)',
    fr: 'Saint-Martin (FR)',
    it: 'Saint-Martin (FR)',
  },
  {
    countryCode: 'MG',
    dialCode: '+261',
    de: 'Madagaskar',
    en: 'Madagascar',
    fr: 'Madagascar',
    it: 'Madagascar',
  },
  {
    countryCode: 'MH',
    dialCode: '+692',
    de: 'Marshall-Inseln',
    en: 'Marshall Islands',
    fr: 'Marshall, Iles',
    it: 'Marshall, Isole',
  },
  {
    countryCode: 'MK',
    dialCode: '+389',
    de: 'Mazedonien, ehemalige jugoslawische Republik',
    en: 'Macedonia, Former Yugoslav Republic of',
    fr: 'Macedoine, ex-République yougoslave de',
    it: 'Macedonia, ex Repubblica iugoslava',
  },
  {
    countryCode: 'ML',
    dialCode: '+223',
    de: 'Mali',
    en: 'Mali',
    fr: 'Mali',
    it: 'Mali',
  },
  {
    countryCode: 'MM',
    dialCode: '+95',
    de: 'Myanmar (Union)',
    en: 'Myanmar (Union of)',
    fr: 'Myanmar (Union de)',
    it: 'Myanmar (Unione)',
  },
  {
    countryCode: 'MN',
    dialCode: '+976',
    de: 'Mongolei',
    en: 'Mongolia',
    fr: 'Mongolie',
    it: 'Mongolia',
  },
  {
    countryCode: 'MO',
    dialCode: '+853',
    de: 'Macao',
    en: 'Macao',
    fr: 'Macao',
    it: 'Macao',
  },
  {
    countryCode: 'MP',
    dialCode: '+1',
    de: 'Marianen-Inseln',
    en: 'Mariana Islands',
    fr: 'Mariannes, Iles',
    it: 'Marianne, Isole',
  },
  {
    countryCode: 'MQ',
    dialCode: '+596',
    de: 'Martinique',
    en: 'Martinique',
    fr: 'Martinique',
    it: 'Martinica',
  },
  {
    countryCode: 'MR',
    dialCode: '+222',
    de: 'Mauretanien',
    en: 'Mauritania',
    fr: 'Mauritanie',
    it: 'Mauritania',
  },
  {
    countryCode: 'MS',
    dialCode: '+1664',
    de: 'Montserrat',
    en: 'Montserrat',
    fr: 'Montserrat',
    it: 'Montserrat',
  },
  {
    countryCode: 'MT',
    dialCode: '+356',
    de: 'Malta',
    en: 'Malta',
    fr: 'Malte',
    it: 'Malta',
  },
  {
    countryCode: 'MU',
    dialCode: '+230',
    de: 'Mauritius, Insel',
    en: 'Mauritius Island',
    fr: 'Maurice, Ile',
    it: 'Maurizio, Isola',
  },
  {
    countryCode: 'MV',
    dialCode: '+960',
    de: 'Malediven',
    en: 'Maldives',
    fr: 'Maldives',
    it: 'Maldive, Isole',
  },
  {
    countryCode: 'MW',
    dialCode: '+265',
    de: 'Malawi',
    en: 'Malawi',
    fr: 'Malawi',
    it: 'Malawi',
  },
  {
    countryCode: 'MX',
    dialCode: '+52',
    de: 'Mexiko',
    en: 'Mexico',
    fr: 'Mexique',
    it: 'Messico',
  },
  {
    countryCode: 'MY',
    dialCode: '+60',
    de: 'Malaysia',
    en: 'Malaysia',
    fr: 'Malaisie',
    it: 'Malaisia',
  },
  {
    countryCode: 'MZ',
    dialCode: '+258',
    de: 'Mosambik',
    en: 'Mozambique',
    fr: 'Mozambique',
    it: 'Mozambico',
  },
  {
    countryCode: 'NA',
    dialCode: '+264',
    de: 'Namibia',
    en: 'Namibia',
    fr: 'Namibie',
    it: 'Namibia',
  },
  {
    countryCode: 'NC',
    dialCode: '+687',
    de: 'Neukaledonien',
    en: 'New Caledonia',
    fr: 'Nouvelle-Calédonie',
    it: 'Nuova Caledonia',
  },
  {
    countryCode: 'NE',
    dialCode: '+227',
    de: 'Niger',
    en: 'Niger',
    fr: 'Niger',
    it: 'Niger',
  },
  {
    countryCode: 'NF',
    dialCode: '+672',
    de: 'Norfolk-Insel',
    en: 'Norfolk Island',
    fr: 'Norfolk, Ile',
    it: 'Norfolk, Isola',
  },
  {
    countryCode: 'NG',
    dialCode: '+234',
    de: 'Nigeria',
    en: 'Nigeria',
    fr: 'Nigeria',
    it: 'Nigeria',
  },
  {
    countryCode: 'NI',
    dialCode: '+505',
    de: 'Nicaragua',
    en: 'Nicaragua',
    fr: 'Nicaragua',
    it: 'Nicaragua',
  },
  {
    countryCode: 'NL',
    dialCode: '+31',
    de: 'Niederlande',
    en: 'Netherlands',
    fr: 'Pays-Bas',
    it: 'Paesi Bassi',
  },
  {
    countryCode: 'NO',
    dialCode: '+47',
    de: 'Norwegen',
    en: 'Norway',
    fr: 'Norvège',
    it: 'Norvegia',
  },
  {
    countryCode: 'NP',
    dialCode: '+977',
    de: 'Nepal',
    en: 'Nepal',
    fr: 'Népal',
    it: 'Nepal',
  },
  {
    countryCode: 'NR',
    dialCode: '+674',
    de: 'Nauru',
    en: 'Nauru',
    fr: 'Nauru',
    it: 'Nauru',
  },
  {
    countryCode: 'NU',
    dialCode: '+683',
    de: 'Niue',
    en: 'Niue',
    fr: 'Niue',
    it: 'Niue',
  },
  {
    countryCode: 'NZ',
    dialCode: '+64',
    de: 'Neuseeland',
    en: 'New Zealand',
    fr: 'Nouvelle-Zélande',
    it: 'Nuova Zelanda',
  },
  {
    countryCode: 'OM',
    dialCode: '+968',
    de: 'Oman',
    en: 'Oman',
    fr: 'Oman',
    it: 'Oman',
  },
  {
    countryCode: 'PA',
    dialCode: '+507',
    de: 'Panama',
    en: 'Panama',
    fr: 'Panama',
    it: 'Panama',
  },
  {
    countryCode: 'PE',
    dialCode: '+51',
    de: 'Peru',
    en: 'Peru',
    fr: 'Pérou',
    it: 'Perù',
  },
  {
    countryCode: 'PF',
    dialCode: '+689',
    de: 'Französisch-Polynesien',
    en: 'French Polynesia',
    fr: 'Polynésie Française',
    it: 'Polinesia francese',
  },
  {
    countryCode: 'PG',
    dialCode: '+675',
    de: 'Papua-Neuguinea',
    en: 'Papua New Guinea',
    fr: 'Papouasie-Nouvelle-Guinée',
    it: 'Papua-Nuova Guinea',
  },
  {
    countryCode: 'PH',
    dialCode: '+63',
    de: 'Philippinen',
    en: 'Philippines',
    fr: 'Philippines',
    it: 'Filippine',
  },
  {
    countryCode: 'PK',
    dialCode: '+92',
    de: 'Pakistan',
    en: 'Pakistan',
    fr: 'Pakistan',
    it: 'Pakistan',
  },
  {
    countryCode: 'PL',
    dialCode: '+48',
    de: 'Polen',
    en: 'Poland',
    fr: 'Pologne',
    it: 'Polonia',
  },
  {
    countryCode: 'PM',
    dialCode: '+508',
    de: 'Saint-Pierre und Miquelon',
    en: 'Saint Pierre and Miquelon',
    fr: 'Saint-Pierre-et-Miquelon',
    it: 'Saint-Pierre e Miquelon',
  },
  {
    countryCode: 'PN',
    dialCode: '+64',
    de: 'Pitcairninseln',
    en: 'Pitcairn Islands',
    fr: 'Pitcairn, Îles',
    it: 'Pitcairn, Isole',
  },
];
