export const countryItems = [
  {
    short: 'PR',
    de: 'Puerto Rico',
    en: 'Puerto Rico',
    fr: 'Porto Rico',
    it: 'Porto Rico',
    area: '+1787',
  },
  {
    short: 'PS',
    de: 'Palästina',
    en: 'Palestine',
    fr: 'Palestine',
    it: 'Palestina',
    area: '',
  },
  {
    short: 'PT',
    de: 'Portugal',
    en: 'Portugal',
    fr: 'Portugal',
    it: 'Portogallo',
    area: '+351',
  },
  {
    short: 'PW',
    de: 'Palau',
    en: 'Palau',
    fr: 'Palau',
    it: 'Palau',
    area: '+680',
  },
  {
    short: 'PY',
    de: 'Paraguay',
    en: 'Paraguay',
    fr: 'Paraguay',
    it: 'Paraguay',
    area: '+595',
  },
  {
    short: 'QA',
    de: 'Qatar',
    en: 'Qatar',
    fr: 'Qatar',
    it: 'Qatar',
    area: '+974',
  },
  {
    short: 'AD',
    de: 'Andorra',
    en: 'Andorra',
    fr: 'Andorre',
    it: 'Andorra',
    area: '+376',
  },
  {
    short: 'AE',
    de: 'Vereinigte Arabische Emirate',
    en: 'United Arab Emirates',
    fr: 'Emirats Arabes Unis',
    it: 'Emirati Arabi Uniti',
    area: '+971',
  },
  {
    short: 'AF',
    de: 'Afghanistan',
    en: 'Afghanistan',
    fr: 'Afghanistan',
    it: 'Afganistan',
    area: '',
  },
  {
    short: 'AG',
    de: 'Antigua und Barbuda',
    en: 'Antigua and Barbuda',
    fr: 'Antigua et Barbuda',
    it: 'Antigua e Barbuda',
    area: '+1268',
  },
  {
    short: 'AI',
    de: 'Anguilla',
    en: 'Anguilla',
    fr: 'Anguilla',
    it: 'Anguilla',
    area: '+1264',
  },
  {
    short: 'AL',
    de: 'Albanien',
    en: 'Albania',
    fr: 'Albanie',
    it: 'Albania',
    area: '',
  },
  {
    short: 'AM',
    de: 'Armenien',
    en: 'Armenia',
    fr: 'Arménie',
    it: 'Armenia',
    area: '+374',
  },
  {
    short: 'AO',
    de: 'Angola',
    en: 'Angola',
    fr: 'Angola',
    it: 'Angola',
    area: '+244',
  },
  {
    short: 'AR',
    de: 'Argentinien',
    en: 'Argentina',
    fr: 'Argentine',
    it: 'Argentina',
    area: '+54',
  },
  {
    short: 'AS',
    de: 'Samoa, amerikanischer Teil',
    en: 'American Samoa',
    fr: 'Samoa, partie américaine',
    it: 'Samoa, parte statunitense',
    area: '',
  },
  {
    short: 'AT',
    de: 'Österreich',
    en: 'Austria',
    fr: 'Autriche',
    it: 'Austria',
    area: '+43',
  },
  {
    short: 'RE',
    de: 'Réunion',
    en: 'Réunion',
    fr: 'Réunion',
    it: 'Riunione',
    area: '+262',
  },
  {
    short: 'AU',
    de: 'Australien',
    en: 'Australia',
    fr: 'Australie',
    it: 'Australia',
    area: '+61',
  },
  {
    short: 'AW',
    de: 'Aruba',
    en: 'Aruba',
    fr: 'Aruba',
    it: 'Aruba',
    area: '+297',
  },
  {
    short: 'AX',
    de: 'Åland',
    en: 'Åland',
    fr: 'Åland',
    it: 'Åland',
    area: '',
  },
  {
    short: 'AZ',
    de: 'Aserbaidschan',
    en: 'Azerbaijan',
    fr: 'Azerbaïdjan',
    it: 'Azerbaigian',
    area: '+994',
  },
  {
    short: 'RO',
    de: 'Rumänien',
    en: 'Romania',
    fr: 'Roumanie',
    it: 'Romania',
    area: '+40',
  },
  {
    short: 'BA',
    de: 'Bosnien-Herzegowina',
    en: 'Bosnia-Herzegovina',
    fr: 'Bosnie-Herzégovine',
    it: 'Bosnia-Erzegovina',
    area: '+387',
  },
  {
    short: 'BB',
    de: 'Barbados',
    en: 'Barbados',
    fr: 'Barbade',
    it: 'Barbados',
    area: '+1246',
  },
  {
    short: 'RS',
    de: 'Serbien',
    en: 'Serbia',
    fr: 'Serbie',
    it: 'Serbia',
    area: '',
  },
  {
    short: 'BD',
    de: 'Bangladesh',
    en: 'Bangladesh',
    fr: 'Bangladesh',
    it: 'Bangladesh',
    area: '+880',
  },
  {
    short: 'BE',
    de: 'Belgien',
    en: 'Belgium',
    fr: 'Belgique',
    it: 'Belgio',
    area: '+32',
  },
  {
    short: 'RU',
    de: 'Russische Föderation',
    en: 'Russian Federation',
    fr: 'Russie (Fédération de)',
    it: 'Russia (Federazione di)',
    area: '+7',
  },
  {
    short: 'BF',
    de: 'Burkina Faso',
    en: 'Burkina Faso',
    fr: 'Burkina Faso',
    it: 'Burkina Faso',
    area: '+226',
  },
  {
    short: 'BG',
    de: 'Bulgarien',
    en: 'Bulgaria',
    fr: 'Bulgarie',
    it: 'Bulgaria',
    area: '+359',
  },
  {
    short: 'RW',
    de: 'Rwanda',
    en: 'Rwanda',
    fr: 'Rwanda',
    it: 'Rwanda',
    area: '+250',
  },
  {
    short: 'BH',
    de: 'Bahrain',
    en: 'Bahrain',
    fr: 'Bahrain',
    it: 'Bahrein',
    area: '+973',
  },
  {
    short: 'BI',
    de: 'Burundi',
    en: 'Burundi',
    fr: 'Burundi',
    it: 'Burundi',
    area: '+257',
  },
  {
    short: 'BJ',
    de: 'Benin',
    en: 'Benin',
    fr: 'Bénin',
    it: 'Benin',
    area: '+229',
  },
  {
    short: 'BL',
    de: 'Saint-Barthélemy',
    en: 'Saint-Barthélemy',
    fr: 'Saint-Barthélemy',
    it: 'Saint-Barthélemy',
    area: '',
  },
  {
    short: 'BM',
    de: 'Bermuda',
    en: 'Bermuda',
    fr: 'Bermudes',
    it: 'Bermude',
    area: '+1441',
  },
  {
    short: 'BN',
    de: 'Brunei',
    en: 'Brunei',
    fr: 'Brunéi',
    it: 'Brunei',
    area: '+673',
  },
  {
    short: 'BO',
    de: 'Bolivien',
    en: 'Bolivia',
    fr: 'Bolivie',
    it: 'Bolivia',
    area: '+591',
  },
  {
    short: 'SA',
    de: 'Saudi-Arabien',
    en: 'Saudi Arabia',
    fr: 'Arabie Saoudite',
    it: 'Arabia Saudita',
    area: '+966',
  },
  {
    short: 'SB',
    de: 'Salomon-Inseln',
    en: 'Salomon Islands',
    fr: 'Salomon, Iles',
    it: 'Salomone, Isole',
    area: '+677',
  },
  {
    short: 'BQ',
    de: 'Bonaire, Sint Eustatius und Saba',
    en: 'Bonaire, Sint Eustatius and Saba',
    fr: 'Bonaire, Saint-Eustache et Saba',
    it: 'Bonaire, Sint-Eustache e Saba',
    area: '',
  },
  {
    short: 'BR',
    de: 'Brasilien',
    en: 'Brazil',
    fr: 'Brésil',
    it: 'Brasile',
    area: '+55',
  },
  {
    short: 'SC',
    de: 'Seychellen',
    en: 'Seychelles',
    fr: 'Seychelles',
    it: 'Seicelle',
    area: '+248',
  },
  {
    short: 'BS',
    de: 'Bahamas',
    en: 'Bahamas',
    fr: 'Bahamas',
    it: 'Bahama',
    area: '+1242',
  },
  {
    short: 'SD',
    de: 'Sudan',
    en: 'Sudan',
    fr: 'Soudan',
    it: 'Sudan',
    area: '+249',
  },
  {
    short: 'BT',
    de: 'Bhutan',
    en: 'Bhutan',
    fr: 'Bhoutan',
    it: 'Bhutan',
    area: '+975',
  },
  {
    short: 'SE',
    de: 'Schweden',
    en: 'Sweden',
    fr: 'Suède',
    it: 'Svezia',
    area: '+46',
  },
  {
    short: 'SG',
    de: 'Singapur',
    en: 'Singapore',
    fr: 'Singapour',
    it: 'Singapore',
    area: '+65',
  },
  {
    short: 'BW',
    de: 'Botswana',
    en: 'Botswana',
    fr: 'Botswana',
    it: 'Botswana',
    area: '+267',
  },
  {
    short: 'SH',
    de: 'St. Helena, Ascension und Tristan da Cunha',
    en: 'Saint Helena, Ascension and Tristan da Cunha',
    fr: 'Sainte-Hélène, Ascension et Tristan da Cunha',
    it: "Sant'Elena, Ascensione e Tristan da Cunha",
    area: '+290',
  },
  {
    short: 'SI',
    de: 'Slowenien',
    en: 'Slovenia',
    fr: 'Slovénie',
    it: 'Slovenia',
    area: '+386',
  },
  {
    short: 'BY',
    de: 'Belarus',
    en: 'Belarus',
    fr: 'Bélarus',
    it: 'Bielorussia',
    area: '+375',
  },
  {
    short: 'BZ',
    de: 'Belize',
    en: 'Belize',
    fr: 'Belize',
    it: 'Belize',
    area: '+501',
  },
  {
    short: 'SK',
    de: 'Slowakei',
    en: 'Slovakia',
    fr: 'Slovaquie',
    it: 'Slovacchia',
    area: '+421',
  },
  {
    short: 'SL',
    de: 'Sierra Leone',
    en: 'Sierra Leone',
    fr: 'Sierra Leone',
    it: 'Sierra Leone',
    area: '+232',
  },
  {
    short: 'SM',
    de: 'San Marino',
    en: 'San Marino',
    fr: 'St-Marin',
    it: 'San Marino',
    area: '+378',
  },
  {
    short: 'SN',
    de: 'Senegal',
    en: 'Senegal',
    fr: 'Sénégal',
    it: 'Senegal',
    area: '+221',
  },
  {
    short: 'SO',
    de: 'Somalia',
    en: 'Somalia',
    fr: 'Somalie',
    it: 'Somalia',
    area: '+252',
  },
  {
    short: 'CA',
    de: 'Kanada',
    en: 'Canada',
    fr: 'Canada',
    it: 'Canada',
    area: '+1',
  },
  {
    short: 'SR',
    de: 'Suriname',
    en: 'Suriname',
    fr: 'Suriname',
    it: 'Suriname',
    area: '+597',
  },
  {
    short: 'CC',
    de: 'Kokos-Insel (Keeling)',
    en: 'Cocos (Keeling) Island',
    fr: 'Cocos (Keeling), Ile des',
    it: 'Cocos, Isola',
    area: '',
  },
  {
    short: 'SS',
    de: 'Südsudan',
    en: 'South Sudan',
    fr: 'Soudan du Sud',
    it: 'Sudan del Sud',
    area: '',
  },
  {
    short: 'CD',
    de: 'Kongo, Demokratische Republik',
    en: 'Congo, Democratic Republic',
    fr: 'Congo, République démocratique',
    it: 'Congo, Repubblica Democratica',
    area: '',
  },
  {
    short: 'ST',
    de: 'São Tomé und Príncipe',
    en: 'São Tomé and Príncipe',
    fr: 'Sao Tomé-et-Principe',
    it: 'São Tomé e Príncipe',
    area: '+239',
  },
  {
    short: 'CF',
    de: 'Zentralafrika',
    en: 'Central African Republic',
    fr: 'Centrafrique',
    it: 'Centrafrica',
    area: '+236',
  },
  {
    short: 'SV',
    de: 'El Salvador',
    en: 'El Salvador',
    fr: 'El Salvador',
    it: 'El Salvador',
    area: '+503',
  },
  {
    short: 'CG',
    de: 'Kongo (Republik)',
    en: 'Congo (Republic)',
    fr: 'Congo (République)',
    it: 'Congo (Repubblica)',
    area: '+242',
  },
  {
    short: 'CH',
    de: 'Schweiz',
    en: 'Switzerland',
    fr: 'Suisse',
    it: 'Svizzera',
    area: '+41',
  },
  {
    short: 'SX',
    de: 'Sint Maarten (NL)',
    en: 'Sint Maarten (NL)',
    fr: 'Sint Maarten (NL)',
    it: 'Sint Maarten (NL)',
    area: '',
  },
  {
    short: 'CI',
    de: 'Elfenbeinküste',
    en: 'Ivory Coast',
    fr: "Côte d'Ivoire",
    it: "Costa d'Avorio",
    area: '',
  },
  {
    short: 'SY',
    de: 'Syrien',
    en: 'Syria',
    fr: 'Syrie',
    it: 'Siria',
    area: '',
  },
  {
    short: 'SZ',
    de: 'Swasiland',
    en: 'Swaziland',
    fr: 'Swaziland',
    it: 'Swaziland',
    area: '+268',
  },
  {
    short: 'CK',
    de: 'Cook-Inseln',
    en: 'Cook Islands',
    fr: 'Cook, Iles',
    it: 'Cook, Isole',
    area: '+682',
  },
  {
    short: 'CL',
    de: 'Chile',
    en: 'Chile',
    fr: 'Chili',
    it: 'Cile',
    area: '+56',
  },
  {
    short: 'CM',
    de: 'Kamerun',
    en: 'Cameroon',
    fr: 'Cameroun',
    it: 'Camerun',
    area: '+237',
  },
  {
    short: 'CN',
    de: 'China (Volksrepublik)',
    en: "China (People's Republic)",
    fr: 'Chine (République populaire)',
    it: 'Cina (Repubblica Popolare)',
    area: '+86',
  },
  {
    short: 'CO',
    de: 'Kolumbien',
    en: 'Colombia',
    fr: 'Colombie',
    it: 'Colombia',
    area: '+57',
  },
  {
    short: 'CR',
    de: 'Costa Rica',
    en: 'Costa Rica',
    fr: 'Costa Rica',
    it: 'Costa Rica',
    area: '+506',
  },
  {
    short: 'TC',
    de: 'Turks und Caicos',
    en: 'Turks and Caicos',
    fr: 'Turques et Caïques',
    it: 'Turks e Caicos',
    area: '+1649',
  },
  {
    short: 'TD',
    de: 'Tschad',
    en: 'Chad',
    fr: 'Tchad',
    it: 'Ciad',
    area: '',
  },
  {
    short: 'CU',
    de: 'Kuba',
    en: 'Cuba',
    fr: 'Cuba',
    it: 'Cuba',
    area: '+53',
  },
  {
    short: 'TF',
    de: 'Französische Süd- und Antarktisgebiete',
    en: 'French Southern and Antarctic Lands',
    fr: 'Terres australes et antarctiques françaises',
    it: 'Terre australi e antartiche francesi',
    area: '',
  },
  {
    short: 'CV',
    de: 'Kapverdische Inseln',
    en: 'Cape Verde',
    fr: 'Cap-Vert, Iles du',
    it: 'Capo Verde, Isole del',
    area: '+238',
  },
  {
    short: 'TG',
    de: 'Togo',
    en: 'Togo',
    fr: 'Togo',
    it: 'Togo',
    area: '+228',
  },
  {
    short: 'TH',
    de: 'Thailand',
    en: 'Thailand',
    fr: 'Thaïlande',
    it: 'Tailandia',
    area: '+66',
  },
  {
    short: 'CW',
    de: 'Curaçao',
    en: 'Curaçao',
    fr: 'Curaçao',
    it: 'Curaçao',
    area: '',
  },
  {
    short: 'CX',
    de: 'Weihnachtsinseln (indischer Ozean)',
    en: 'Christmas Island (Indian Ocean)',
    fr: 'Christmas, Ile (Océan indien)',
    it: 'Christmas, Isola (Oceano indiano)',
    area: '',
  },
  {
    short: 'CY',
    de: 'Zypern',
    en: 'Cyprus',
    fr: 'Chypre',
    it: 'Cipro',
    area: '+90392',
  },
  {
    short: 'TJ',
    de: 'Tadschikistan',
    en: 'Tajikistan',
    fr: 'Tadjikistan',
    it: 'Tagiskistan',
    area: '+7',
  },
  {
    short: 'CZ',
    de: 'Tschechische Republik',
    en: 'Czech Republic',
    fr: 'Tchèque (République)',
    it: 'Ceca (Repubblica)',
    area: '+42',
  },
  {
    short: 'TK',
    de: 'Tokelau',
    en: 'Tokelau',
    fr: 'Tokélaou',
    it: 'Tokelau',
    area: '',
  },
  {
    short: 'TL',
    de: 'Timor-Leste',
    en: 'Timor-Leste',
    fr: 'Timor-Leste',
    it: 'Timor-Leste',
    area: '',
  },
  {
    short: 'TM',
    de: 'Turkmenistan',
    en: 'Turkmenistan',
    fr: 'Turkménistan',
    it: 'Turkmenistan',
    area: '+7',
  },
  {
    short: 'TN',
    de: 'Tunesien',
    en: 'Tunisia',
    fr: 'Tunisie',
    it: 'Tunisia',
    area: '+216',
  },
  {
    short: 'TO',
    de: 'Tonga',
    en: 'Tonga',
    fr: 'Tonga',
    it: 'Tonga',
    area: '+676',
  },
  {
    short: 'TR',
    de: 'Türkei',
    en: 'Turkey',
    fr: 'Turquie',
    it: 'Turchia',
    area: '+90',
  },
  {
    short: 'TT',
    de: 'Trinidad und Tobago',
    en: 'Trinidad and Tobago',
    fr: 'Trinité et Tobago',
    it: 'Trinidad e Tobago',
    area: '+1868',
  },
  {
    short: 'DE',
    de: 'Deutschland',
    en: 'Germany',
    fr: 'Allemagne',
    it: 'Germania',
    area: '+49',
  },
  {
    short: 'TV',
    de: 'Tuvalu',
    en: 'Tuvalu',
    fr: 'Tuvalu',
    it: 'Tuvalu',
    area: '+688',
  },
  {
    short: 'TW',
    de: 'Taiwan (Chinesisches Taipeh)',
    en: 'Taiwan (Chinese Taipei)',
    fr: 'Taiwan (Taipei chinois)',
    it: 'Taiwan (Cina Taipei)',
    area: '+886',
  },
  {
    short: 'DJ',
    de: 'Djibouti',
    en: 'Djibouti',
    fr: 'Djibouti',
    it: 'Gibuti',
    area: '+253',
  },
  {
    short: 'TZ',
    de: 'Tansania',
    en: 'Tanzania',
    fr: 'Tanzanie',
    it: 'Tanzania',
    area: '',
  },
  {
    short: 'DK',
    de: 'Dänemark',
    en: 'Denmark',
    fr: 'Danemark',
    it: 'Danimarca',
    area: '+45',
  },
  {
    short: 'DM',
    de: 'Dominica',
    en: 'Dominica',
    fr: 'Dominique',
    it: 'Dominica',
    area: '+1809',
  },
  {
    short: 'DO',
    de: 'Dominikanische Republik',
    en: 'Dominican Republic',
    fr: 'Dominicaine (République)',
    it: 'Dominicana (Repubblica)',
    area: '+1809',
  },
  {
    short: 'UA',
    de: 'Ukraine',
    en: 'Ukraine',
    fr: 'Ukraine',
    it: 'Ucraina',
    area: '+380',
  },
  {
    short: 'UG',
    de: 'Uganda',
    en: 'Uganda',
    fr: 'Ouganda',
    it: 'Uganda',
    area: '+256',
  },
  {
    short: 'DZ',
    de: 'Algerien',
    en: 'Algeria',
    fr: 'Algérie',
    it: 'Algeria',
    area: '+213',
  },
  {
    short: 'UM',
    de: 'Amerikanische Überseeinseln, kleinere',
    en: 'United States Minor Outlying Islands',
    fr: 'Iles mineures éloignées des Etats-Unis',
    it: 'Isole Minori (USA)',
    area: '',
  },
  {
    short: 'EC',
    de: 'Ekuador',
    en: 'Ecuador',
    fr: 'Equateur',
    it: 'Equatore',
    area: '+593',
  },
  {
    short: 'US',
    de: 'Vereinigte Staaten von Amerika',
    en: 'United States of America',
    fr: "Etats-Unis d'Amérique",
    it: "Stati Uniti d'America",
    area: '+1',
  },
  {
    short: 'EE',
    de: 'Estland',
    en: 'Estonia',
    fr: 'Estonie',
    it: 'Estonia',
    area: '+372',
  },
  {
    short: 'EG',
    de: 'Ägypten',
    en: 'Egypt',
    fr: 'Egypte',
    it: 'Egitto',
    area: '+20',
  },
  {
    short: 'EH',
    de: 'Westsahara',
    en: 'Western Sahara',
    fr: 'Sahara occidental',
    it: 'Sahara Occidentale',
    area: '',
  },
  {
    short: 'UY',
    de: 'Uruguay',
    en: 'Uruguay',
    fr: 'Uruguay',
    it: 'Uruguay',
    area: '+598',
  },
  {
    short: 'UZ',
    de: 'Usbekistan',
    en: 'Uzbekistan',
    fr: 'Ouzbékistan',
    it: 'Uzbekistan',
    area: '+7',
  },
  {
    short: 'VA',
    de: 'Vatikanstadt',
    en: 'Vatican City',
    fr: 'Cité du Vatican',
    it: 'Città del Vaticano',
    area: '+379',
  },
  {
    short: 'ER',
    de: 'Eritrea',
    en: 'Eritrea',
    fr: 'Erythrée',
    it: 'Eritrea',
    area: '+291',
  },
  {
    short: 'VC',
    de: 'St. Vincent und die Grenadinen',
    en: 'Saint Vincent and the Grenadines',
    fr: 'Saint-Vincent-et-les-Grenadines',
    it: 'Saint Vincent e Grenadine',
    area: '',
  },
  {
    short: 'ES',
    de: 'Spanien',
    en: 'Spain',
    fr: 'Espagne',
    it: 'Spagna',
    area: '+34',
  },
  {
    short: 'ET',
    de: 'Äthiopien',
    en: 'Ethiopia',
    fr: 'Ethiopie',
    it: 'Etiopia',
    area: '+251',
  },
  {
    short: 'VE',
    de: 'Venezuela',
    en: 'Venezuela',
    fr: 'Venezuela',
    it: 'Venezuela',
    area: '+58',
  },
  {
    short: 'VG',
    de: 'Britische Jungferninseln',
    en: 'British Virgin Islands',
    fr: 'IIes Vierges britanniques',
    it: 'Isole Vergini britanniche',
    area: '+84',
  },
  {
    short: 'VI',
    de: 'Jungferninseln (USA)',
    en: 'Virgin Islands (USA)',
    fr: 'Iles Vierges (Etats-Unis)',
    it: 'Isole Vergini (USA)',
    area: '+84',
  },
  {
    short: 'VN',
    de: 'Vietnam',
    en: 'Vietnam',
    fr: 'Viêt-Nam',
    it: 'Vietnam',
    area: '+84',
  },
  {
    short: 'VU',
    de: 'Vanuatu',
    en: 'Vanuatu',
    fr: 'Vanuatu',
    it: 'Vanuatu',
    area: '+678',
  },
  {
    short: 'FI',
    de: 'Finnland',
    en: 'Finland',
    fr: 'Finlande',
    it: 'Finlandia',
    area: '+358',
  },
  {
    short: 'FJ',
    de: 'Fidschi',
    en: 'Fiji',
    fr: 'Fidji',
    it: 'Figi',
    area: '+679',
  },
  {
    short: 'FK',
    de: 'Falkland-Inseln',
    en: 'Falkland Islands',
    fr: 'Falkland, Iles',
    it: 'Falkland, Isole',
    area: '+500',
  },
  {
    short: 'FM',
    de: 'Mikronesien (Föderierte Staaten von)',
    en: 'Micronesia (Federated States OF)',
    fr: 'Micronésie (Etats fédérés)',
    it: 'Micronesia (Stati federati)',
    area: '+691',
  },
  {
    short: 'FO',
    de: 'Färöer-Inseln',
    en: 'Faroe Islands',
    fr: 'Féroé, Iles',
    it: 'Faeröer, Isole',
    area: '+298',
  },
  {
    short: 'FR',
    de: 'Frankreich',
    en: 'France',
    fr: 'France',
    it: 'Francia',
    area: '+33',
  },
  {
    short: 'WF',
    de: 'Wallis und Futuna',
    en: 'Wallis and Futuna Islands',
    fr: 'Wallis et Futuna',
    it: 'Wallis e Futuna',
    area: '+681',
  },
  {
    short: 'GA',
    de: 'Gabun',
    en: 'Gabon',
    fr: 'Gabon',
    it: 'Gabon',
    area: '+241',
  },
  {
    short: 'GB',
    de: 'Grossbritannien und Nordirland',
    en: 'Great Britain and Northern Ireland',
    fr: 'Grande-Bretagne et Irlande du Nord',
    it: 'Gran Bretagna e Irlanda del Nord',
    area: '+44',
  },
  {
    short: 'WS',
    de: 'Samoa',
    en: 'Samoa',
    fr: 'Samoa',
    it: 'Samoa',
    area: '',
  },
  {
    short: 'GD',
    de: 'Grenada',
    en: 'Grenada',
    fr: 'Grenade',
    it: 'Grenada',
    area: '+1473',
  },
  {
    short: 'GE',
    de: 'Georgien',
    en: 'Georgia',
    fr: 'Géorgie',
    it: 'Georgia',
    area: '+7880',
  },
  {
    short: 'GF',
    de: 'Französisch-Guyana',
    en: 'French Guiana',
    fr: 'Guyane française',
    it: 'Guiana Francese',
    area: '+594',
  },
  {
    short: 'GG',
    de: 'Guernsey',
    en: 'Guernsey',
    fr: 'Guernsey',
    it: 'Guernsey',
    area: '',
  },
  {
    short: 'GH',
    de: 'Ghana',
    en: 'Ghana',
    fr: 'Ghana',
    it: 'Ghana',
    area: '+233',
  },
  {
    short: 'GI',
    de: 'Gibraltar',
    en: 'Gibraltar',
    fr: 'Gibraltar',
    it: 'Gibilterra',
    area: '+350',
  },
  {
    short: 'GL',
    de: 'Grönland',
    en: 'Greenland',
    fr: 'Groenland',
    it: 'Groenlandia',
    area: '+299',
  },
  {
    short: 'GM',
    de: 'Gambia',
    en: 'Gambia',
    fr: 'Gambie',
    it: 'Gambia',
    area: '+220',
  },
  {
    short: 'GN',
    de: 'Guinea (Republik)',
    en: 'Guinea (Republic)',
    fr: 'Guinée (République)',
    it: 'Guinea (Repubblica)',
    area: '+224',
  },
  {
    short: 'GP',
    de: 'Guadeloupe',
    en: 'Guadeloupe',
    fr: 'Guadeloupe',
    it: 'Guadalupa',
    area: '+590',
  },
  {
    short: 'GQ',
    de: 'Äquatorial-Guinea',
    en: 'Equatorial Guinea',
    fr: 'Guinée équatoriale',
    it: 'Guinea equatoriale',
    area: '+240',
  },
  {
    short: 'GR',
    de: 'Griechenland',
    en: 'Greece',
    fr: 'Grèce',
    it: 'Grecia',
    area: '+30',
  },
  {
    short: 'GS',
    de: 'Südgeorgien und die südlichen Sandwichinseln',
    en: 'South Georgia and the south Sandwich Islands',
    fr: 'Géorgie du sud et les îles Sandwich du sud',
    it: 'Georgia australe e le isole Sandwich australe',
    area: '',
  },
  {
    short: 'GT',
    de: 'Guatemala',
    en: 'Guatemala',
    fr: 'Guatemala',
    it: 'Guatemala',
    area: '+502',
  },
  {
    short: 'GU',
    de: 'Guam',
    en: 'Guam',
    fr: 'Guam',
    it: 'Guam',
    area: '+671',
  },
  {
    short: 'GW',
    de: 'Guinea-Bissau',
    en: 'Guinea-Bissau',
    fr: 'Guinée-Bissau',
    it: 'Guinea-Bissau',
    area: '+245',
  },
  {
    short: 'GY',
    de: 'Guyana',
    en: 'Guyana',
    fr: 'Guyane',
    it: 'Guiana',
    area: '+592',
  },
  {
    short: 'XK',
    de: 'Kosovo',
    en: 'Kosovo',
    fr: 'Kosovo',
    it: 'Kosovo',
    area: '',
  },
  {
    short: 'XY',
    de: 'unbekannt',
    en: 'unknown',
    fr: 'inconnu',
    it: 'sconosciuto',
    area: '',
  },
  {
    short: 'HK',
    de: 'Hongkong',
    en: 'Hong Kong',
    fr: 'Hong-Kong',
    it: 'Hongkong',
    area: '+852',
  },
  {
    short: 'HN',
    de: 'Honduras',
    en: 'Honduras',
    fr: 'Honduras',
    it: 'Honduras',
    area: '+504',
  },
  {
    short: 'HR',
    de: 'Kroatien',
    en: 'Croatia',
    fr: 'Croatie',
    it: 'Croazia',
    area: '+385',
  },
  {
    short: 'HT',
    de: 'Haiti',
    en: 'Haiti',
    fr: 'Haïti',
    it: 'Haiti',
    area: '+509',
  },
  {
    short: 'YE',
    de: 'Jemen',
    en: 'Yemen',
    fr: 'Yémen',
    it: 'Yemen',
    area: '+969',
  },
  {
    short: 'HU',
    de: 'Ungarn',
    en: 'Hungary',
    fr: 'Hongrie',
    it: 'Ungheria',
    area: '+36',
  },
  {
    short: 'ID',
    de: 'Indonesien',
    en: 'Indonesia',
    fr: 'Indonésie',
    it: 'Indonesia',
    area: '+62',
  },
  {
    short: 'YT',
    de: 'Mayotte',
    en: 'Mayotte',
    fr: 'Mayotte',
    it: 'Mayotte',
    area: '+269',
  },
  {
    short: 'IE',
    de: 'Irland',
    en: 'Ireland',
    fr: 'Irlande',
    it: 'Irlanda',
    area: '+353',
  },
  {
    short: 'IL',
    de: 'Israel',
    en: 'Israel',
    fr: 'Israël',
    it: 'Israele',
    area: '+972',
  },
  {
    short: 'IM',
    de: 'Man, Insel',
    en: 'Isle of Man',
    fr: 'Man, Ile de',
    it: 'Man, Isola di',
    area: '',
  },
  {
    short: 'IN',
    de: 'Indien',
    en: 'India',
    fr: 'Inde',
    it: 'India',
    area: '+91',
  },
  {
    short: 'IO',
    de: 'Britisches Territorium im Indischen Ozean',
    en: 'British Indian Ocean Territory',
    fr: "Territoire britannique de l'océan Indien",
    it: "Territorio britannico dell'Oceano Indiano",
    area: '',
  },
  {
    short: 'ZA',
    de: 'Südafrika',
    en: 'South Africa',
    fr: 'Afrique du Sud',
    it: 'Sudafrica',
    area: '+27',
  },
  {
    short: 'IQ',
    de: 'Irak',
    en: 'Iraq',
    fr: 'Iraq',
    it: 'Iraq',
    area: '+964',
  },
  {
    short: 'IR',
    de: 'Iran',
    en: 'Iran',
    fr: 'Iran',
    it: 'Iran',
    area: '+98',
  },
  {
    short: 'IS',
    de: 'Island',
    en: 'Iceland',
    fr: 'Islande',
    it: 'Islanda',
    area: '+354',
  },
  {
    short: 'IT',
    de: 'Italien',
    en: 'Italy',
    fr: 'Italie',
    it: 'Italia',
    area: '+39',
  },
  {
    short: 'ZM',
    de: 'Sambia',
    en: 'Zambia',
    fr: 'Zambie',
    it: 'Zambia',
    area: '+260',
  },
  {
    short: 'JE',
    de: 'Jersey',
    en: 'Jersey',
    fr: 'Jersey',
    it: 'Jersey',
    area: '',
  },
  {
    short: 'ZW',
    de: 'Zimbabwe',
    en: 'Zimbabwe',
    fr: 'Zimbabwe',
    it: 'Zimbabwe',
    area: '+263',
  },
  {
    short: 'JM',
    de: 'Jamaika',
    en: 'Jamaica',
    fr: 'Jamaïque',
    it: 'Giamaica',
    area: '+1876',
  },
  {
    short: 'JO',
    de: 'Jordanien',
    en: 'Jordan',
    fr: 'Jordanie',
    it: 'Giordania',
    area: '+962',
  },
  {
    short: 'JP',
    de: 'Japan',
    en: 'Japan',
    fr: 'Japon',
    it: 'Giappone',
    area: '+81',
  },
  {
    short: 'KE',
    de: 'Kenia',
    en: 'Kenya',
    fr: 'Kenya',
    it: 'Kenya',
    area: '+254',
  },
  {
    short: 'KG',
    de: 'Kirgisistan',
    en: 'Kyrgyzstan',
    fr: 'Kirghizistan',
    it: 'Kirghizistan',
    area: '+996',
  },
  {
    short: 'KH',
    de: 'Kambodscha',
    en: 'Cambodia',
    fr: 'Cambodge',
    it: 'Cambogia',
    area: '+855',
  },
  {
    short: 'KI',
    de: 'Kiribati',
    en: 'Kiribati',
    fr: 'Kiribati',
    it: 'Kiribati',
    area: '+686',
  },
  {
    short: 'KM',
    de: 'Komoren',
    en: 'Comoros',
    fr: 'Comores',
    it: 'Comore',
    area: '+269',
  },
  {
    short: 'KN',
    de: 'St. Christoph (St. Kitts) und Nevis',
    en: 'St. Christopher (St. Kitts) and Nevis',
    fr: 'St. Christophe (St. Kitts) et Nevis',
    it: 'San Cristoforo (St. Kitts) e Nevis',
    area: '+1869',
  },
  {
    short: 'KP',
    de: 'Korea, demokratische Volksrepublik (Nordkorea)',
    en: "Korea, Democratic People's Republic of (North Korea)",
    fr: 'Corée, République populaire démocratique (Corée du Nord)',
    it: 'Corea, Repubblica popolare democratica (Corea del Nord)',
    area: '+850',
  },
  {
    short: 'KR',
    de: 'Korea, Republik (Südkorea)',
    en: 'Korea, Republic of (South Korea)',
    fr: 'Corée, République (Corée du Sud)',
    it: 'Corea, Repubblica (Corea del Sud)',
    area: '+82',
  },
  {
    short: 'KW',
    de: 'Kuwait',
    en: 'Kuwait',
    fr: 'Kuwait',
    it: 'Kuwait',
    area: '+965',
  },
  {
    short: 'KY',
    de: 'Cayman',
    en: 'Cayman Islands',
    fr: 'Cayman',
    it: 'Cayman',
    area: '+1345',
  },
  {
    short: 'KZ',
    de: 'Kasachstan',
    en: 'Kazakhstan',
    fr: 'Kazakhstan',
    it: 'Kazakistan',
    area: '+7',
  },
  {
    short: 'LA',
    de: 'Laos',
    en: 'Laos',
    fr: 'Laos',
    it: 'Laos',
    area: '+856',
  },
  {
    short: 'LB',
    de: 'Libanon',
    en: 'Lebanon',
    fr: 'Liban',
    it: 'Libano',
    area: '+961',
  },
  {
    short: 'LC',
    de: 'St. Lucia',
    en: 'St. Lucia',
    fr: 'St. Lucie',
    it: 'St. Lucia',
    area: '',
  },
  {
    short: 'LI',
    de: 'Liechtenstein',
    en: 'Liechtenstein',
    fr: 'Liechtenstein',
    it: 'Liechtenstein',
    area: '+417',
  },
  {
    short: 'LK',
    de: 'Sri Lanka',
    en: 'Sri Lanka',
    fr: 'Sri Lanka',
    it: 'Sri Lanka',
    area: '+94',
  },
  {
    short: 'LR',
    de: 'Liberia',
    en: 'Liberia',
    fr: 'Libéria',
    it: 'Liberia',
    area: '+231',
  },
  {
    short: 'LS',
    de: 'Lesotho',
    en: 'Lesotho',
    fr: 'Lesotho',
    it: 'Lesotho',
    area: '+266',
  },
  {
    short: 'LT',
    de: 'Litauen',
    en: 'Lithuania',
    fr: 'Lituanie',
    it: 'Lituania',
    area: '+370',
  },
  {
    short: 'LU',
    de: 'Luxemburg',
    en: 'Luxembourg',
    fr: 'Luxembourg',
    it: 'Lussemburgo',
    area: '+352',
  },
  {
    short: 'LV',
    de: 'Lettland',
    en: 'Latvia',
    fr: 'Lettonie',
    it: 'Lettonia',
    area: '+371',
  },
  {
    short: 'LY',
    de: 'Libyen',
    en: 'Libya',
    fr: 'Libye',
    it: 'Libia',
    area: '+218',
  },
  {
    short: 'MA',
    de: 'Marokko',
    en: 'Morocco',
    fr: 'Maroc',
    it: 'Marocco',
    area: '+212',
  },
  {
    short: 'MC',
    de: 'Monaco',
    en: 'Monaco',
    fr: 'Monaco',
    it: 'Monaco',
    area: '+377',
  },
  {
    short: 'MD',
    de: 'Moldova',
    en: 'Moldova',
    fr: 'Moldova',
    it: 'Moldova',
    area: '+373',
  },
  {
    short: 'ME',
    de: 'Montenegro',
    en: 'Montenegro',
    fr: 'Monténégro',
    it: 'Montenegro',
    area: '',
  },
  {
    short: 'MF',
    de: 'Saint-Martin (FR)',
    en: 'Saint-Martin (FR)',
    fr: 'Saint-Martin (FR)',
    it: 'Saint-Martin (FR)',
    area: '',
  },
  {
    short: 'MG',
    de: 'Madagaskar',
    en: 'Madagascar',
    fr: 'Madagascar',
    it: 'Madagascar',
    area: '+261',
  },
  {
    short: 'MH',
    de: 'Marshall-Inseln',
    en: 'Marshall Islands',
    fr: 'Marshall, Iles',
    it: 'Marshall, Isole',
    area: '+692',
  },
  {
    short: 'MK',
    de: 'Mazedonien, ehemalige jugoslawische Republik',
    en: 'Macedonia, Former Yugoslav Republic of',
    fr: 'Macedoine, ex-République yougoslave de',
    it: 'Macedonia, ex Repubblica iugoslava',
    area: '+389',
  },
  {
    short: 'ML',
    de: 'Mali',
    en: 'Mali',
    fr: 'Mali',
    it: 'Mali',
    area: '+223',
  },
  {
    short: 'MM',
    de: 'Myanmar (Union)',
    en: 'Myanmar (Union of)',
    fr: 'Myanmar (Union de)',
    it: 'Myanmar (Unione)',
    area: '',
  },
  {
    short: 'MN',
    de: 'Mongolei',
    en: 'Mongolia',
    fr: 'Mongolie',
    it: 'Mongolia',
    area: '+976',
  },
  {
    short: 'MO',
    de: 'Macao',
    en: 'Macao',
    fr: 'Macao',
    it: 'Macao',
    area: '+853',
  },
  {
    short: 'MP',
    de: 'Marianen-Inseln',
    en: 'Mariana Islands',
    fr: 'Mariannes, Iles',
    it: 'Marianne, Isole',
    area: '',
  },
  {
    short: 'MQ',
    de: 'Martinique',
    en: 'Martinique',
    fr: 'Martinique',
    it: 'Martinica',
    area: '+596',
  },
  {
    short: 'MR',
    de: 'Mauretanien',
    en: 'Mauritania',
    fr: 'Mauritanie',
    it: 'Mauritania',
    area: '+222',
  },
  {
    short: 'MS',
    de: 'Montserrat',
    en: 'Montserrat',
    fr: 'Montserrat',
    it: 'Montserrat',
    area: '+1664',
  },
  {
    short: 'MT',
    de: 'Malta',
    en: 'Malta',
    fr: 'Malte',
    it: 'Malta',
    area: '+356',
  },
  {
    short: 'MU',
    de: 'Mauritius, Insel',
    en: 'Mauritius Island',
    fr: 'Maurice, Ile',
    it: 'Maurizio, Isola',
    area: '',
  },
  {
    short: 'MV',
    de: 'Malediven',
    en: 'Maldives',
    fr: 'Maldives',
    it: 'Maldive, Isole',
    area: '+960',
  },
  {
    short: 'MW',
    de: 'Malawi',
    en: 'Malawi',
    fr: 'Malawi',
    it: 'Malawi',
    area: '+265',
  },
  {
    short: 'MX',
    de: 'Mexiko',
    en: 'Mexico',
    fr: 'Mexique',
    it: 'Messico',
    area: '+52',
  },
  {
    short: 'MY',
    de: 'Malaysia',
    en: 'Malaysia',
    fr: 'Malaisie',
    it: 'Malaisia',
    area: '+60',
  },
  {
    short: 'MZ',
    de: 'Mosambik',
    en: 'Mozambique',
    fr: 'Mozambique',
    it: 'Mozambico',
    area: '+258',
  },
  {
    short: 'NA',
    de: 'Namibia',
    en: 'Namibia',
    fr: 'Namibie',
    it: 'Namibia',
    area: '+264',
  },
  {
    short: 'NC',
    de: 'Neukaledonien',
    en: 'New Caledonia',
    fr: 'Nouvelle-Calédonie',
    it: 'Nuova Caledonia',
    area: '+687',
  },
  {
    short: 'NE',
    de: 'Niger',
    en: 'Niger',
    fr: 'Niger',
    it: 'Niger',
    area: '+227',
  },
  {
    short: 'NF',
    de: 'Norfolk-Insel',
    en: 'Norfolk Island',
    fr: 'Norfolk, Ile',
    it: 'Norfolk, Isola',
    area: '+672',
  },
  {
    short: 'NG',
    de: 'Nigeria',
    en: 'Nigeria',
    fr: 'Nigeria',
    it: 'Nigeria',
    area: '+234',
  },
  {
    short: 'NI',
    de: 'Nicaragua',
    en: 'Nicaragua',
    fr: 'Nicaragua',
    it: 'Nicaragua',
    area: '+505',
  },
  {
    short: 'NL',
    de: 'Niederlande',
    en: 'Netherlands',
    fr: 'Pays-Bas',
    it: 'Paesi Bassi',
    area: '+31',
  },
  {
    short: 'NO',
    de: 'Norwegen',
    en: 'Norway',
    fr: 'Norvège',
    it: 'Norvegia',
    area: '+47',
  },
  {
    short: 'NP',
    de: 'Nepal',
    en: 'Nepal',
    fr: 'Népal',
    it: 'Nepal',
    area: '+977',
  },
  {
    short: 'NR',
    de: 'Nauru',
    en: 'Nauru',
    fr: 'Nauru',
    it: 'Nauru',
    area: '+674',
  },
  {
    short: 'NU',
    de: 'Niue',
    en: 'Niue',
    fr: 'Niue',
    it: 'Niue',
    area: '+683',
  },
  {
    short: 'NZ',
    de: 'Neuseeland',
    en: 'New Zealand',
    fr: 'Nouvelle-Zélande',
    it: 'Nuova Zelanda',
    area: '+64',
  },
  {
    short: 'OM',
    de: 'Oman',
    en: 'Oman',
    fr: 'Oman',
    it: 'Oman',
    area: '+968',
  },
  {
    short: 'PA',
    de: 'Panama',
    en: 'Panama',
    fr: 'Panama',
    it: 'Panama',
    area: '+507',
  },
  {
    short: 'PE',
    de: 'Peru',
    en: 'Peru',
    fr: 'Pérou',
    it: 'Perù',
    area: '+51',
  },
  {
    short: 'PF',
    de: 'Französisch-Polynesien',
    en: 'French Polynesia',
    fr: 'Polynésie Française',
    it: 'Polinesia francese',
    area: '+689',
  },
  {
    short: 'PG',
    de: 'Papua-Neuguinea',
    en: 'Papua New Guinea',
    fr: 'Papouasie-Nouvelle-Guinée',
    it: 'Papua-Nuova Guinea',
    area: '+675',
  },
  {
    short: 'PH',
    de: 'Philippinen',
    en: 'Philippines',
    fr: 'Philippines',
    it: 'Filippine',
    area: '+63',
  },
  {
    short: 'PK',
    de: 'Pakistan',
    en: 'Pakistan',
    fr: 'Pakistan',
    it: 'Pakistan',
    area: '',
  },
  {
    short: 'PL',
    de: 'Polen',
    en: 'Poland',
    fr: 'Pologne',
    it: 'Polonia',
    area: '+48',
  },
  {
    short: 'PM',
    de: 'Saint-Pierre und Miquelon',
    en: 'Saint Pierre and Miquelon',
    fr: 'Saint-Pierre-et-Miquelon',
    it: 'Saint-Pierre e Miquelon',
    area: '',
  },
  {
    short: 'PN',
    de: 'Pitcairninseln',
    en: 'Pitcairn Islands',
    fr: 'Pitcairn, Îles',
    it: 'Pitcairn, Isole',
    area: '',
  },
];
