export type Icon =
  | 'arrow-left'
  | 'arrow-right'
  | 'collapse'
  | 'document'
  | 'download'
  | 'email'
  | 'expand'
  | 'mobile'
  | 'phone'
  | 'plus'
  | 'search'
  | 'upload'
  | 'cloud-upload'
  | 'axa-logo'
  | 'axa-logo-open';
