import withReact from '../../../utils/with-react';
import AXADropdown from './index';

export default createElement => ({
  'data-test-id': dataTestId,
  defaultTitle,
  label,
  required,
  refId,
  items,
  value,
  native,
  invalid,
  checkMark,
  error,
  disabled,
  className = '',
  onChange = () => {},
  onFocus = () => {},
  onBlur = () => {},
}) =>
  withReact(createElement)(AXADropdown.tagName, {
    'data-test-id': dataTestId,
    label,
    required,
    refId,
    defaultTitle,
    items,
    value,
    native,
    invalid,
    checkMark,
    error,
    disabled,
    onChange,
    onFocus,
    onBlur,
    className,
    isReact: true,
  });
