name: Github to Jira Issues

on: 
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create Jira Issue
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: GA
        issuetype: Build
        summary: |
          Build completed for ${{ github.repository }}
        description: |
          Compare branch
        fields: '{"customfield_10171": "test"}'

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"